version: 2

updates:
  - package-ecosystem: "maven"
    directories:
      - "/"
      - "/acceptance-tests"
      - "/generate-race-cpcplus"
      - "/qrda3-update-measures"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      spring:
        patterns:
          - "org.springframework*:*"
      aws-sdk:
        patterns:
          - "com.amazonaws*:*"
      junit:
        patterns:
          - "org.junit*:*"