project_name       = "qppsf"
region             = "us-east-1"
environment        = "dev"
pagerduty_email    = "qpp-final-scoring-devops@semanticbits.com"
owner              = "qpp-final-scoring-devops@semanticbits.com"
git-origin         = "https://github.com/CMSgov/qpp-conversion-tool.git"
application        = "qpp-conversiontool"
sensitivity        = "PII/PHI"