package gov.cms.qpp.conversion.api.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.encryption.DoNotEncrypt;
import com.google.common.base.Objects;

import java.util.Date;

@DynamoDBTable(tableName="ConversionMetadata")
public final class Metadata {
	private String uuid;
	private String tin;
	private String npi;
	private Date createdDate;
	private String apm; //encrypt?
	private long submissionYear;
	private String submissionLocator;
	private String fileName;
	private boolean overallStatus;
	private boolean conversionStatus;
	private boolean validationStatus;
	private boolean cpc;
	private String conversionErrorLocator;
	private String validationErrorLocator;


	@DynamoDBHashKey(attributeName = "Uuid")
	@DynamoDBAutoGeneratedKey
	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="CreateDate")
	@DynamoDBAutoGeneratedTimestamp(strategy= DynamoDBAutoGenerateStrategy.CREATE)
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@DynamoDBAttribute(attributeName="Tin")
	public String getTin() {
		return tin;
	}

	public void setTin(String tin) {
		this.tin = tin;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="Npi")
	public String getNpi() {
		return npi;
	}

	public void setNpi(String npi) {
		this.npi = npi;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="Apm")
	public String getApm() {
		return apm;
	}

	public void setApm(String apm) {
		this.apm = apm;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="SubmissionYear")
	public long getSubmissionYear() {
		return submissionYear;
	}

	public void setSubmissionYear(long submissionYear) {
		this.submissionYear = submissionYear;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="SubmissonLocator")
	public String getSubmissionLocator() {
		return submissionLocator;
	}

	public void setSubmissionLocator(String submissionLocator) {
		this.submissionLocator = submissionLocator;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="FileName")
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="OverallStatus")
	public boolean isOverallStatus() {
		return overallStatus;
	}

	public void setOverallStatus(boolean overallStatus) {
		this.overallStatus = overallStatus;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="ConversionStatus")
	public boolean isConversionStatus() {
		return conversionStatus;
	}

	public void setConversionStatus(boolean conversionStatus) {
		this.conversionStatus = conversionStatus;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="ValidationStatus")
	public boolean isValidationStatus() {
		return validationStatus;
	}

	public void setValidationStatus(boolean validationStatus) {
		this.validationStatus = validationStatus;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="Cpc")
	public boolean isCpc() {
		return cpc;
	}

	public void setCpc(boolean cpc) {
		this.cpc = cpc;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="ConversionErrorLocator")
	public String getConversionErrorLocator() {
		return conversionErrorLocator;
	}

	public void setConversionErrorLocator(String conversionErrorLocator) {
		this.conversionErrorLocator = conversionErrorLocator;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="ValidationErrorLocator")
	public String getValidationErrorLocator() {
		return validationErrorLocator;
	}

	public void setValidationErrorLocator(String validationErrorLocator) {
		this.validationErrorLocator = validationErrorLocator;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (!(o instanceof Metadata)) return false;
		Metadata metadata = (Metadata) o;
		return submissionYear == metadata.submissionYear &&
				overallStatus == metadata.overallStatus &&
				conversionStatus == metadata.conversionStatus &&
				validationStatus == metadata.validationStatus &&
				cpc == metadata.cpc &&
				Objects.equal(uuid, metadata.uuid) &&
				Objects.equal(tin, metadata.tin) &&
				Objects.equal(npi, metadata.npi) &&
				Objects.equal(createdDate, metadata.createdDate) &&
				Objects.equal(apm, metadata.apm) &&
				Objects.equal(submissionLocator, metadata.submissionLocator) &&
				Objects.equal(fileName, metadata.fileName) &&
				Objects.equal(conversionErrorLocator, metadata.conversionErrorLocator) &&
				Objects.equal(validationErrorLocator, metadata.validationErrorLocator);
	}

	@Override
	public int hashCode() {
		return Objects.hashCode(uuid, tin, npi, createdDate, apm, submissionYear,
				submissionLocator, fileName, overallStatus, conversionStatus, validationStatus,
				cpc, conversionErrorLocator, validationErrorLocator);
	}
}
