package gov.cms.qpp.conversion.api.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "qppConversionFiles")
public class QppFileEntity {

	private String TIN;

	private String dateTime;

	public QppFileEntity() {
	}

	@DynamoDBHashKey(attributeName = "TIN")
	@DynamoDBAutoGeneratedKey
	public String getTIN() {
		return TIN;
	}

	public void setTIN(final String TIN) {
		this.TIN = TIN;
	}

	public String getDateTime() {
		return dateTime;
	}

	public void setDateTime(final String dateTime) {
		this.dateTime = dateTime;
	}
}
