#!/bin/bash

# Dependency Update Helper Script
# Usage: ./scripts/update-dependencies.sh [aws|all]

set -e

echo "🔍 QPP Conversion Tool - Dependency Update Helper"
echo "================================================="

# Function to check Maven dependency updates
check_maven_updates() {
    echo "📦 Checking for Maven dependency updates..."
    mvn versions:display-dependency-updates -DprocessDependencyManagement=false
    echo ""
    
    echo "📦 Checking for Maven plugin updates..."
    mvn versions:display-plugin-updates
    echo ""
}

# Function to update AWS SDK specifically
update_aws_sdk() {
    echo "🔧 Updating AWS SDK to latest version..."
    
    # Get current AWS version
    CURRENT_VERSION=$(grep '<aws.version>' pom.xml | sed 's/.*<aws.version>\(.*\)<\/aws.version>.*/\1/')
    echo "Current AWS SDK version: $CURRENT_VERSION"
    
    # Check for latest AWS SDK version
    echo "Checking for latest AWS SDK version..."
    LATEST_VERSION=$(mvn versions:resolve-ranges -Dincludes="com.amazonaws:aws-java-sdk-core" -q | grep "aws-java-sdk-core" | tail -1 | sed 's/.*-> \([0-9.]*\).*/\1/' || echo "")
    
    if [ ! -z "$LATEST_VERSION" ] && [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
        echo "Latest AWS SDK version: $LATEST_VERSION"
        read -p "Update AWS SDK from $CURRENT_VERSION to $LATEST_VERSION? (y/N): " confirm
        
        if [[ $confirm =~ ^[Yy]$ ]]; then
            echo "Updating aws.version property..."
            sed -i.bak "s/<aws.version>$CURRENT_VERSION<\/aws.version>/<aws.version>$LATEST_VERSION<\/aws.version>/" pom.xml
            rm pom.xml.bak 2>/dev/null || true
            
            echo "✅ Updated AWS SDK version to $LATEST_VERSION"
            echo "🧪 Running tests to validate update..."
            
            mvn --batch-mode clean compile test -q -Dskip.generate=true
            if [ $? -eq 0 ]; then
                echo "✅ Tests passed! Update looks good."
            else
                echo "❌ Tests failed. Reverting change..."
                git checkout pom.xml
                exit 1
            fi
        fi
    else
        echo "✅ AWS SDK is already at the latest version ($CURRENT_VERSION)"
    fi
}

# Function to create a dependency update PR
create_update_pr() {
    local update_type=$1
    local branch_name="deps/update-$update_type-$(date +%Y%m%d)"
    
    echo "🌿 Creating branch: $branch_name"
    git checkout -b "$branch_name"
    
    echo "📝 Committing changes..."
    git add pom.xml
    git commit -m "deps: update $update_type dependencies

- Updated $update_type dependencies to latest versions
- Validated with test suite
- Auto-generated by update script"
    
    echo "🚀 Pushing branch..."
    git push -u origin "$branch_name"
    
    # Create PR using GitHub CLI if available
    if command -v gh &> /dev/null; then
        echo "📋 Creating pull request..."
        gh pr create \
            --title "deps: update $update_type dependencies" \
            --body "Automated dependency update for $update_type.

## Changes
- Updated $update_type dependencies to latest versions
- All tests pass ✅

## Validation
- [ ] Integration tests pass
- [ ] Security scan clean
- [ ] Performance impact assessed

/cc @your-team" \
            --label "dependencies" \
            --assignee "@me"
    else
        echo "💡 GitHub CLI not installed. Please create PR manually for branch: $branch_name"
    fi
}

# Main script logic
case "${1:-all}" in
    "aws")
        echo "🎯 Targeting AWS SDK updates only"
        update_aws_sdk
        if git diff --quiet pom.xml; then
            echo "No changes made."
        else
            create_update_pr "aws-sdk"
        fi
        ;;
    "all")
        echo "🎯 Checking all dependencies"
        check_maven_updates
        echo ""
        echo "💡 Use 'mvn versions:use-latest-versions' to update dependencies"
        echo "💡 Use '$0 aws' to update just AWS SDK"
        ;;
    *)
        echo "Usage: $0 [aws|all]"
        echo "  aws  - Update AWS SDK only"
        echo "  all  - Check all dependency updates (default)"
        exit 1
        ;;
esac

echo ""
echo "✨ Done!"