pipeline {
    agent {
        label "worker"
    }

     environment {
        WORKSPACE_DIR="infrastructure"
        PROJ_DIR="dynamodb-backup-notifier"
    }

    stages {
        stage('Cloning Git Repo') {
            steps{
                git branch: 'develop', url: 'https://github.com/CMSgov/qpp-conversion-tool.git'
            }
        }
        stage('Building Docker Image for script Execution') {
            steps {
                sh """#!/bin/bash
                cd ./${WORKSPACE_DIR}/${PROJ_DIR}; docker build -t alpine/aws-cli:latest .
                IMG_ID="\$(docker images --filter=reference=alpine/aws-cli --format {{.ID}})"
                docker run ${'$'}IMG_ID
                """
            }
    post {
        always {
            cleanWs()
        }
    }
        }
    }
}
