---
- hosts: ec2
  remote_user: pkendall
  tasks:
  - name: Install Java
    apt:
      name: default-jre
    become: true
  - name: Install Tomcat
    apt:
      name: tomcat8
    become: true
  - name: Start Tomcat
    service:
      name: tomcat8
      enabled: yes
      state: started
    become: true
  - name: Copy QPP Conversion Tools
    copy:
      src: ./resources/java-conversion-tool.jar
      dest: ~/
  - name: Copy QRDA3 files
    copy:
      src: ../qrda-files/
      dest: ~/qrda-files/
