service: aws-endpoint-trigger-s3

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: us-east-1
custom:
  defaultStage: dev
  profiles:
    dev: lambdauser
    prod: prodProfile

functions:
  simpleEndpoint:
    handler: endpoint.endpoint
    events:
      - http:
          path: ping
          method: get
          cors: true
  moveFile:
    handler: move_file.move_file
    events:
      - s3:
          bucket: flexion-lambdatest
          event: s3:ObjectCreated:*
      - s3: flexion-lambdatest-destination
