---
name: Checkov for Terraform
on:
  pull_request:
    branches:
      - develop
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infrastructure
          skip_check: CKV_AWS_18,CKV_AWS_23,CKV_AWS_115,CKV_AWS_116,CKV_AWS_117,CKV_AWS_40,CKV_AWS_50,CKV_AWS_144,CKV_AWS_145,CKV_AWS_131,CKV_AWS_103,CKV_AWS_51,CKV_AWS_136,CKV_AWS_158
          framework: terraform