---
name: Checkov for Terraform
on:
  pull_request:
    branches:
      - develop

env:
  CHECKOV_OUTPUT_CODE_LINE_LIMIT: 255
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infrastructure
          skip_check: CKV_AWS_316,CKV_AWS_18,CKV_AWS_23,CKV_AWS_115,CKV_AWS_116,CKV_AWS_117,CKV_AWS_40,CKV_AWS_50,CKV_AWS_144,CKV_AWS_145,CKV_AWS_131,CKV_AWS_103,CKV_AWS_51,CKV_AWS_136,CKV_AWS_158,CKV_AWS_173,CKV_AWS_32,CKV_AWS_337,CKV_AWS_272,CKV_AWS_61,CKV2_AWS_62,CKV2_AWS_355,CKV2_AWS_365,CKV2_AWS_67,CKV_AWS_355,CKV_AWS_290
          framework: terraform
