name: Codebuild trigger to deploy it to impl environment
on:
  push:
    branches: [ 'release/**' ]

jobs:
  build:
    name: conversion tool codebuil job
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Print branch name
        run: |
          echo "Current branch: ${GITHUB_REF##*/}"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::730335206644:role/delegatedadmin/developer/qppa-github-actions-role
          aws-region: us-east-1

      - name: Execute ssh command
        run: |
          aws codebuild start-build --project-name "qppa-conversion-tool-impl" --source-version "${GITHUB_REF##*/}"